---

version: "3"

set: [errexit, pipefail, nounset]
shopt: [globstar]

dotenv: [".env.local", ".env"]

tasks:
  init:
    silent: true
    desc: Setup project
    cmds:
      - |
        nix run nixpkgs#lefthook install
    sources:
      - ./lefthook.yaml
      - ./flake.nix
  install:
    silent: true
    desc: Install project
    cmds:
      - |
        nix profile install . --refresh
