require("lspkind").init({
  mode = "symbol_text",
  -- preset = "codicons",
  symbol_map = {
    Text = "📄 Text",
    Method = "🔧 Method",
    Function = "🔵 Function",
    Constructor = "🏭 Constructor",
    Field = "🌾 Field",
    Variable = "🔶 Variable",
    Class = "🏰 Class",
    Interface = "🌐 Interface",
    Module = "📦 Module",
    Property = "🏠 Property",
    Unit = "⚙️ Unit",
    Value = "💎 Value",
    Enum = "🔢 Enum",
    Keyword = "🔑 Keyword",
    Snippet = "📝 Snippet",
    Color = "🎨 Color",
    File = "📄 File",
    Reference = "🔗 Reference",
    Folder = "📂 Folder",
    EnumMember = "🔢 Enum Member",
    Constant = "🔒 Constant",
    Struct = "🏛️ Struct",
    Event = "🎉 Event",
    Operator = "🔗 Operator",
    TypeParameter = "🆔 Type Parameter",
    Copilot = "🤖 Copilot",
  },
})
