# -*- mode: ruby -*-
# vi: set ft=ruby :
# VirtualBox version : 5.2.18
# Vagrant version : 2.1.5
# Nfs version : 3
# Nfs protocol : udp

VM = 'newvm'
DISK01 = VM + '-data.vdi'

Vagrant.configure("2") do |config|
  # Global
  # Attention à ne pas mettre le /home/vagrant -> override la clef SSH
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.name = VM
    vb.memory = "2048"
    vb.cpus = 2
    vb.linked_clone = true
    vb.gui = false

    # Create Hard Drive
    unless File.exists?(DISK01)
      vb.customize ['createmedium',
                    'disk',
                    '--filename', DISK01,
                    '--variant', 'Fixed',
                    '--size', 30 * 1024]
    end

    vb.customize ['storageattach', :id,
                  '--storagectl', 'IDE',
                  '--port', 1, '--device', 0,
                  '--type', 'hdd',
                  '--medium', DISK01]
  end

  config.vm.define VM do |centos|
    centos.vm.hostname = VM
    centos.vm.box = "centos/7"
    centos.vm.network "private_network", ip: "192.168.100.200"
    config.vm.network :forwarded_port, host: 5000, guest: 5000
  end
  script = './src/scripts/'
  cfg = './src/confs/'

  # Init
  config.vm.provision "file", source: cfg + "bashrc", destination: "/home/vagrant/.bashrc", run: "always"
  config.vm.provision "init", type: "shell", run: "never",
    :path => script + "init.sh", :args => "--install"
end
